#!/usr/bin/env node
var importResolve = require('./index');

// spits out a master dist file with all your wonderful stylesheet 
// things concatenated 
let fin = process.argv[2]
let fout = process.argv[3]
let fext = process.argv[4] || "scss"

importResolve({
    "ext": fext,
    "pathToMain": fin,
     "output": fout
});